jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # <--- Actualización clave

      - name: Set up Python
        uses: actions/setup-python@v5 # <--- Versión profesional estable
        with:
          python-version: '3.9'
          cache: 'pip' # Activa el caché para bajar el tiempo de 41s a ~20s
