name: Produccion Automatizada 10x
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick fonts-liberation
          sudo sed -i 's/domain="path" rights="none" pattern="@\"/domain="path" rights="read|write" pattern="@\"/g' /etc/ImageMagick-6/policy.xml

      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install requests==2.31.0 moviepy==1.0.3 imageio-ffmpeg==0.4.9
          # No usamos la descarga manual de ffmpeg para ahorrar tiempo y evitar errores

      - name: Run Factory
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
        run: python main.py
